name: resqreact
description: A Flutter application for fall detection and emergency alerts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sensors_plus: ^4.0.2
  permission_handler: ^11.0.0
  geolocator: ^10.0.0
  shared_preferences: ^2.2.2
  # Animation packages
  flutter_animate: ^4.5.0
  lottie: ^2.7.0
  animate_do: ^3.3.0
  # UI enhancement packages
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  shimmer: ^3.0.0
  # Added for Android compatibility
  device_info_plus: ^9.1.1
  # Android intent for direct SMS sending
  android_intent_plus: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/animations/