name: resq_react
description: A Flutter application for fall detection and emergency alerts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  sensors_plus: ^2.0.2
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  shared_preferences: ^2.0.17
  # Removed flutter_local_notifications to fix the Linux plugin error

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/